# Generated by Django 4.0.3 on 2022-08-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_rename_answer_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='문선미', max_length=50),
            preserve_default=False,
        ),
    ]
